server:
  port: 8000
spring:
  application:
    name: driver-management
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
